version: '3'

services:
  wuekabel_db:
    image: mariadb
    restart: always
    volumes:
      - ./conf/create_all.sql:/docker-entrypoint-initdb.d/00_create_all.sql
    environment:
      - MYSQL_ROOT_PASSWORD=12344321

  wuekabel_server:
    build: .
    image: wuekabel
    ports:
      - 9090:9000
    tty: true
    stdin_open: true
    links:
      - wuekabel_db:wuekabel_db
    depends_on:
      - wuekabel_db